# Generated by Django 5.0.1 on 2024-04-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_cpu_alter_item_gpu_alter_item_ram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='item',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Reserved By'),
        ),
        migrations.AddField(
            model_name='item',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Return Date'),
        ),
    ]
