# Generated by Django 5.0.1 on 2024-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_site_only',
            field=models.BooleanField(default=False),
        ),
    ]
